server:
  port: 8088
  servlet:
    context-path: /cinema
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_cinema?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bac22111
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

jwt:
  secretKey: KJfhrflyl7DKpWYDch8WBiaNMvyuy1uXcrZkmLJfOO6X7yW8DJegUouy35tHN6dw
  valid-duration: 900 # in seconds
  refreshable-duration: 86400 # in seconds