server:
  port: 8088
  servlet:
    context-path: /cinema
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking_cinema?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: bac22111
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true